version: "0.2"
env:
  shell: bash
phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
      - rustup install stable
      - rustup toolchain install nightly --component rust-src
      - cargo install bpf-linker
      - yum update -y
      - yum install -y llvm
  build:
    commands:
      - cargo build --release
artifacts:
  files:
    - target/release/narcd
    - codedeploy/*
    - service/*
    - appspec.yml
    - narcd.toml
cache:
  paths:
    - $HOME/.cargo/registry/**/*
